### ISSUE TITLE
Split roles into their own files and add tutorial page

### ISSUE THREAD

**Issue by Malivil** [Malivil/TTT-Custom-Roles#74]
### Role Progress
- [x] ROLE_INNOCENT https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_TRAITOR https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_DETECTIVE https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_JESTER https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_SWAPPER https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_GLITCH https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_PHANTOM https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_HYPNOTIST https://github.com/NoxxFlame/TTT-Custom-Roles/pull/110
- [x] ROLE_REVENGER https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_DRUNK https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_CLOWN https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_DEPUTY https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_IMPERSONATOR https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_BEGGAR https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_OLDMAN https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_MERCENARY https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_BODYSNATCHER https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_VETERAN https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_ASSASSIN https://github.com/NoxxFlame/TTT-Custom-Roles/pull/110
- [x] ROLE_KILLER https://github.com/NoxxFlame/TTT-Custom-Roles/pull/110
- [x] ROLE_ZOMBIE https://github.com/NoxxFlame/TTT-Custom-Roles/pull/110
- [x] ROLE_VAMPIRE https://github.com/NoxxFlame/TTT-Custom-Roles/pull/110
- [x] ROLE_DOCTOR https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_QUACK https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_PARASITE https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_TRICKSTER https://github.com/NoxxFlame/TTT-Custom-Roles/pull/110
- [x] ROLE_PARAMEDIC https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_MADSCIENTIST https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_PALADIN https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_TRACKER https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114
- [x] ROLE_MEDIUM https://github.com/NoxxFlame/TTT-Custom-Roles/pull/114

### Not Fully Extracted Roles
- Deputy/Impersonator
   - Not going to split out all of the shared functionality for these because they depend on eachother. Creating hooks and external configurations for "detective-like" roles it not really feasible because the settings that work off of eachother (like the "use_detective_icon" convars) are strictly set up for two roles and cannot easily be made dynamic.
- Glitch
   - A lot of the Glitch functionality will not get split out due to the complexity and hard integration

**Comment by ianthina** [comment]
Killer should be high priority as an example to link to in the Custom Win Condition section of CREATE_YOUR_OWN_ROLE.md

**Comment by Malivil** [comment]
Why do we need another example?

**Comment by ianthina** [comment]
The killer is a bit more clear than saying [your logic here], and also there are three custom role mods that use the exact same win condition, so it's a commonly needed logic.

**Comment by Malivil** [comment]
WIP on this branch: https://github.com/Malivil/TTT-Custom-Roles/tree/feature_rolesplit

**Comment by Malivil** [comment]
Now being done on https://github.com/Malivil/TTT-Custom-Roles/tree/feature_misc along with everything else

**Comment by Malivil** [comment]
Refocusing this issue into completing the split and tutorial creation for all roles

**Comment by Malivil** [comment]
This is as complete as it's going to be
